# Gas Configuration

[gas]

[gas.flows.resource_lock]
open = 0
fill = 77298
claim = 122793

[gas.flows.permit2_escrow]
open = 146306
fill = 77298
claim = 60084

[gas.flows.eip3009_escrow]
open = 130254
fill = 77298
claim = 60084
