# Network Configuration

[networks.10]
input_settler_address = "0x2778258002a69a0cB1DfD29b360a0bB1654C8652"
output_settler_address = "0x2404F8e3c37c002c89bA78086a119e68E3fF8824"
input_settler_compact_address = "0x7dfFC9e7db5a96887666c1a6D215E5d3Fb306d69"
the_compact_address = "0x00000000000000171ede64904551eedf3c6c9788"
allocator_address = "0x191688B2Ff5Be8F0A5BCAB3E819C900a810FAaf6"


[[networks.10.rpc_urls]]
http = "https://mainnet.optimism.io"

[[networks.10.tokens]]
address = "0xc0b782920B2DE8b55f08FC98004Eb5c7d4fBf287"
symbol = "USDC"
decimals = 6

[networks.8453]
input_settler_address = "0x2778258002a69a0cB1DfD29b360a0bB1654C8652"
output_settler_address = "0x2404F8e3c37c002c89bA78086a119e68E3fF8824"
input_settler_compact_address = "0x7dfFC9e7db5a96887666c1a6D215E5d3Fb306d69"
the_compact_address = "0x00000000000000171ede64904551eedf3c6c9788"
allocator_address = "0x191688B2Ff5Be8F0A5BCAB3E819C900a810FAaf6"

[[networks.8453.rpc_urls]]
http = "https://mainnet.base.org"

[[networks.8453.tokens]]
address = "0xc0b782920B2DE8b55f08FC98004Eb5c7d4fBf287"
symbol = "USDC"
decimals = 6
