# Network Configuration

[networks.10]
input_settler_address = "0x2778258002a69a0cB1DfD29b360a0bB1654C8652"
output_settler_address = "0x2404F8e3c37c002c89bA78086a119e68E3fF8824"
input_settler_compact_address = "0x7dfFC9e7db5a96887666c1a6D215E5d3Fb306d69"
the_compact_address = "0x00000000000000171ede64904551eedf3c6c9788"
allocator_address = "0x191688B2Ff5Be8F0A5BCAB3E819C900a810FAaf6"


[[networks.10.rpc_urls]]
http = "https://mainnet.optimism.io"

[[networks.10.tokens]]
address = "0xc0b782920B2DE8b55f08FC98004Eb5c7d4fBf287"
symbol = "Fake-USDC"
decimals = 6

[networks.42161]
input_settler_address = "0x79750615FD0c3DBE3bBCD7e8E7BDdCbB554b10a8"
output_settler_address = "0x28E8D349d76bf9d553452bF6f02279196E7c5929"
input_settler_compact_address = "0xCC4Ef1264489c40DcD674c7Fe6edf49cD2C40a6A"
the_compact_address = "0x00000000000000171ede64904551eedf3c6c9788"
allocator_address = "0xb8Eb0f7851B4F5E44cFE21C856FAb5A6378AD280"


[[networks.42161.rpc_urls]]
http = "https://arb1.arbitrum.io/rpc"

[[networks.42161.tokens]]
address = "0x7e13E59a15E4703a54a0976dDd970F8Fe52d3a76"
symbol = "Fake-USDC"
decimals = 6

[networks.8453]
input_settler_address = "0x2778258002a69a0cB1DfD29b360a0bB1654C8652"
output_settler_address = "0x2404F8e3c37c002c89bA78086a119e68E3fF8824"
input_settler_compact_address = "0x7dfFC9e7db5a96887666c1a6D215E5d3Fb306d69"
the_compact_address = "0x00000000000000171ede64904551eedf3c6c9788"
allocator_address = "0x191688B2Ff5Be8F0A5BCAB3E819C900a810FAaf6"

[[networks.8453.rpc_urls]]
http = "https://mainnet.base.org"

[[networks.8453.tokens]]
address = "0xc0b782920B2DE8b55f08FC98004Eb5c7d4fBf287"
symbol = "Fake-USDC"
decimals = 6
