[networks.11155420]
input_settler_address = "0x1F0b9d6984f5f9187Db70469085f7935453b815F"
output_settler_address = "0x923aa6CC898540092616f97cA770FFb8080354Fc"
input_settler_compact_address = "0x086e28545bB8494C6041225922A705877AE5362A"
the_compact_address = "0x00000000000000171ede64904551eedf3c6c9788"
allocator_address = "0x565466528d126141ddb5c7d558803f79d9b66a6d"
rpc_indexing_delay_seconds = 10


[[networks.11155420.rpc_urls]]
http = "https://sepolia.optimism.io"

[[networks.11155420.tokens]]
address = "0x191688B2Ff5Be8F0A5BCAB3E819C900a810FAaf6"
symbol = "USDC"
decimals = 6

[networks.84532]
input_settler_address = "0x6C0428cc521CC418A8842d46d413F5F96775c67B"
output_settler_address = "0xC450A11afb68731833BE13225A88ecdad7D7Ed52"
input_settler_compact_address = "0xa7B995442F909849F96B5ED07ff7f58E57a41fc9"
the_compact_address = "0x00000000000000171ede64904551eedf3c6c9788"
allocator_address = "0x04bb6e565f0067e0411528e2d3a55a712d9a8b32"
rpc_indexing_delay_seconds = 2

[[networks.84532.rpc_urls]]
http = "https://sepolia.base.org"

[[networks.84532.tokens]]
address = "0x73c83DAcc74bB8a704717AC09703b959E74b9705"
symbol = "USDC"
decimals = 6
